package pl.springboot.movies.models;

public enum Genre {
    ACTION, ADVENTURE, ANIMATION, BIOGRAPHY, COMEDY, CRIME, DOCUMENTARY, DRAMA, FAMILY, FANTASY,
    HISTORY, HORROR, MUSIC, MUSICAL, MYSTERY, ROMANCE, SCI_FI, SHORT, SPORT, SUPERHERO, THRILLER, WAR, WESTERN
}
